package com.tongtech.client.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

public final class CommonHeader {
  private CommonHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 protoType = 1;</code>
     */
    int getProtoType();

    /**
     * <code>int32 verNo = 2;</code>
     */
    int getVerNo();

    /**
     * <code>int32 commandType = 3;</code>
     */
    int getCommandType();

    /**
     * <pre>
     * Java客户端使用 
     * </pre>
     *
     * <code>int32 requestId = 4;</code>
     */
    int getRequestId();
  }
  /**
   * Protobuf type {@code Common}
   */
  public  static final class Common extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Common)
      CommonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Common.newBuilder() to construct.
    private Common(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Common() {
      protoType_ = 0;
      verNo_ = 0;
      commandType_ = 0;
      requestId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Common(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              protoType_ = input.readInt32();
              break;
            }
            case 16: {

              verNo_ = input.readInt32();
              break;
            }
            case 24: {

              commandType_ = input.readInt32();
              break;
            }
            case 32: {

              requestId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonHeader.internal_static_Common_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonHeader.internal_static_Common_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Common.class, Builder.class);
    }

    public static final int PROTOTYPE_FIELD_NUMBER = 1;
    private int protoType_;
    /**
     * <code>int32 protoType = 1;</code>
     */
    public int getProtoType() {
      return protoType_;
    }

    public static final int VERNO_FIELD_NUMBER = 2;
    private int verNo_;
    /**
     * <code>int32 verNo = 2;</code>
     */
    public int getVerNo() {
      return verNo_;
    }

    public static final int COMMANDTYPE_FIELD_NUMBER = 3;
    private int commandType_;
    /**
     * <code>int32 commandType = 3;</code>
     */
    public int getCommandType() {
      return commandType_;
    }

    public static final int REQUESTID_FIELD_NUMBER = 4;
    private int requestId_;
    /**
     * <pre>
     * Java客户端使用 
     * </pre>
     *
     * <code>int32 requestId = 4;</code>
     */
    public int getRequestId() {
      return requestId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (protoType_ != 0) {
        output.writeInt32(1, protoType_);
      }
      if (verNo_ != 0) {
        output.writeInt32(2, verNo_);
      }
      if (commandType_ != 0) {
        output.writeInt32(3, commandType_);
      }
      if (requestId_ != 0) {
        output.writeInt32(4, requestId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (protoType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, protoType_);
      }
      if (verNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, verNo_);
      }
      if (commandType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, commandType_);
      }
      if (requestId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, requestId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Common)) {
        return super.equals(obj);
      }
      Common other = (Common) obj;

      boolean result = true;
      result = result && (getProtoType()
          == other.getProtoType());
      result = result && (getVerNo()
          == other.getVerNo());
      result = result && (getCommandType()
          == other.getCommandType());
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProtoType();
      hash = (37 * hash) + VERNO_FIELD_NUMBER;
      hash = (53 * hash) + getVerNo();
      hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCommandType();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Common parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Common parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Common parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Common parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Common parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Common parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Common parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Common parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Common parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Common parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Common parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Common parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Common prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common)
        CommonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonHeader.internal_static_Common_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonHeader.internal_static_Common_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Common.class, Builder.class);
      }

      // Construct using CommonHeader.Common.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        protoType_ = 0;

        verNo_ = 0;

        commandType_ = 0;

        requestId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonHeader.internal_static_Common_descriptor;
      }

      public Common getDefaultInstanceForType() {
        return Common.getDefaultInstance();
      }

      public Common build() {
        Common result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Common buildPartial() {
        Common result = new Common(this);
        result.protoType_ = protoType_;
        result.verNo_ = verNo_;
        result.commandType_ = commandType_;
        result.requestId_ = requestId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Common) {
          return mergeFrom((Common)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Common other) {
        if (other == Common.getDefaultInstance()) return this;
        if (other.getProtoType() != 0) {
          setProtoType(other.getProtoType());
        }
        if (other.getVerNo() != 0) {
          setVerNo(other.getVerNo());
        }
        if (other.getCommandType() != 0) {
          setCommandType(other.getCommandType());
        }
        if (other.getRequestId() != 0) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Common parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Common) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int protoType_ ;
      /**
       * <code>int32 protoType = 1;</code>
       */
      public int getProtoType() {
        return protoType_;
      }
      /**
       * <code>int32 protoType = 1;</code>
       */
      public Builder setProtoType(int value) {
        
        protoType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 protoType = 1;</code>
       */
      public Builder clearProtoType() {
        
        protoType_ = 0;
        onChanged();
        return this;
      }

      private int verNo_ ;
      /**
       * <code>int32 verNo = 2;</code>
       */
      public int getVerNo() {
        return verNo_;
      }
      /**
       * <code>int32 verNo = 2;</code>
       */
      public Builder setVerNo(int value) {
        
        verNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 verNo = 2;</code>
       */
      public Builder clearVerNo() {
        
        verNo_ = 0;
        onChanged();
        return this;
      }

      private int commandType_ ;
      /**
       * <code>int32 commandType = 3;</code>
       */
      public int getCommandType() {
        return commandType_;
      }
      /**
       * <code>int32 commandType = 3;</code>
       */
      public Builder setCommandType(int value) {
        
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 commandType = 3;</code>
       */
      public Builder clearCommandType() {
        
        commandType_ = 0;
        onChanged();
        return this;
      }

      private int requestId_ ;
      /**
       * <pre>
       * Java客户端使用 
       * </pre>
       *
       * <code>int32 requestId = 4;</code>
       */
      public int getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * Java客户端使用 
       * </pre>
       *
       * <code>int32 requestId = 4;</code>
       */
      public Builder setRequestId(int value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Java客户端使用 
       * </pre>
       *
       * <code>int32 requestId = 4;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Common)
    }

    // @@protoc_insertion_point(class_scope:Common)
    private static final Common DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Common();
    }

    public static Common getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Common>
        PARSER = new com.google.protobuf.AbstractParser<Common>() {
      public Common parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Common(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Common> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Common> getParserForType() {
      return PARSER;
    }

    public Common getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SysinfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sysinfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 totalMemorySize = 1;</code>
     */
    long getTotalMemorySize();

    /**
     * <code>uint64 freeMemorySize = 2;</code>
     */
    long getFreeMemorySize();

    /**
     * <code>uint64 txflow = 3;</code>
     */
    long getTxflow();

    /**
     * <code>uint64 rxflow = 4;</code>
     */
    long getRxflow();

    /**
     * <code>uint64 totalDiskSize = 5;</code>
     */
    long getTotalDiskSize();

    /**
     * <code>uint64 freeDiskSize = 6;</code>
     */
    long getFreeDiskSize();

    /**
     * <code>uint32 uptime = 7;</code>
     */
    int getUptime();

    /**
     * <code>float cpuOccupy = 8;</code>
     */
    float getCpuOccupy();

    /**
     * <code>uint32 processState = 9;</code>
     */
    int getProcessState();

    /**
     * <code>uint32 cpuNum = 10;</code>
     */
    int getCpuNum();

    /**
     * <code>repeated float loadavg = 11;</code>
     */
    java.util.List<Float> getLoadavgList();
    /**
     * <code>repeated float loadavg = 11;</code>
     */
    int getLoadavgCount();
    /**
     * <code>repeated float loadavg = 11;</code>
     */
    float getLoadavg(int index);
  }
  /**
   * Protobuf type {@code Sysinfo}
   */
  public  static final class Sysinfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Sysinfo)
      SysinfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sysinfo.newBuilder() to construct.
    private Sysinfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sysinfo() {
      totalMemorySize_ = 0L;
      freeMemorySize_ = 0L;
      txflow_ = 0L;
      rxflow_ = 0L;
      totalDiskSize_ = 0L;
      freeDiskSize_ = 0L;
      uptime_ = 0;
      cpuOccupy_ = 0F;
      processState_ = 0;
      cpuNum_ = 0;
      loadavg_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sysinfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              totalMemorySize_ = input.readUInt64();
              break;
            }
            case 16: {

              freeMemorySize_ = input.readUInt64();
              break;
            }
            case 24: {

              txflow_ = input.readUInt64();
              break;
            }
            case 32: {

              rxflow_ = input.readUInt64();
              break;
            }
            case 40: {

              totalDiskSize_ = input.readUInt64();
              break;
            }
            case 48: {

              freeDiskSize_ = input.readUInt64();
              break;
            }
            case 56: {

              uptime_ = input.readUInt32();
              break;
            }
            case 69: {

              cpuOccupy_ = input.readFloat();
              break;
            }
            case 72: {

              processState_ = input.readUInt32();
              break;
            }
            case 80: {

              cpuNum_ = input.readUInt32();
              break;
            }
            case 93: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                loadavg_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000400;
              }
              loadavg_.add(input.readFloat());
              break;
            }
            case 90: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400) && input.getBytesUntilLimit() > 0) {
                loadavg_ = new java.util.ArrayList<Float>();
                mutable_bitField0_ |= 0x00000400;
              }
              while (input.getBytesUntilLimit() > 0) {
                loadavg_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
          loadavg_ = java.util.Collections.unmodifiableList(loadavg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonHeader.internal_static_Sysinfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonHeader.internal_static_Sysinfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sysinfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int TOTALMEMORYSIZE_FIELD_NUMBER = 1;
    private long totalMemorySize_;
    /**
     * <code>uint64 totalMemorySize = 1;</code>
     */
    public long getTotalMemorySize() {
      return totalMemorySize_;
    }

    public static final int FREEMEMORYSIZE_FIELD_NUMBER = 2;
    private long freeMemorySize_;
    /**
     * <code>uint64 freeMemorySize = 2;</code>
     */
    public long getFreeMemorySize() {
      return freeMemorySize_;
    }

    public static final int TXFLOW_FIELD_NUMBER = 3;
    private long txflow_;
    /**
     * <code>uint64 txflow = 3;</code>
     */
    public long getTxflow() {
      return txflow_;
    }

    public static final int RXFLOW_FIELD_NUMBER = 4;
    private long rxflow_;
    /**
     * <code>uint64 rxflow = 4;</code>
     */
    public long getRxflow() {
      return rxflow_;
    }

    public static final int TOTALDISKSIZE_FIELD_NUMBER = 5;
    private long totalDiskSize_;
    /**
     * <code>uint64 totalDiskSize = 5;</code>
     */
    public long getTotalDiskSize() {
      return totalDiskSize_;
    }

    public static final int FREEDISKSIZE_FIELD_NUMBER = 6;
    private long freeDiskSize_;
    /**
     * <code>uint64 freeDiskSize = 6;</code>
     */
    public long getFreeDiskSize() {
      return freeDiskSize_;
    }

    public static final int UPTIME_FIELD_NUMBER = 7;
    private int uptime_;
    /**
     * <code>uint32 uptime = 7;</code>
     */
    public int getUptime() {
      return uptime_;
    }

    public static final int CPUOCCUPY_FIELD_NUMBER = 8;
    private float cpuOccupy_;
    /**
     * <code>float cpuOccupy = 8;</code>
     */
    public float getCpuOccupy() {
      return cpuOccupy_;
    }

    public static final int PROCESSSTATE_FIELD_NUMBER = 9;
    private int processState_;
    /**
     * <code>uint32 processState = 9;</code>
     */
    public int getProcessState() {
      return processState_;
    }

    public static final int CPUNUM_FIELD_NUMBER = 10;
    private int cpuNum_;
    /**
     * <code>uint32 cpuNum = 10;</code>
     */
    public int getCpuNum() {
      return cpuNum_;
    }

    public static final int LOADAVG_FIELD_NUMBER = 11;
    private java.util.List<Float> loadavg_;
    /**
     * <code>repeated float loadavg = 11;</code>
     */
    public java.util.List<Float>
        getLoadavgList() {
      return loadavg_;
    }
    /**
     * <code>repeated float loadavg = 11;</code>
     */
    public int getLoadavgCount() {
      return loadavg_.size();
    }
    /**
     * <code>repeated float loadavg = 11;</code>
     */
    public float getLoadavg(int index) {
      return loadavg_.get(index);
    }
    private int loadavgMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (totalMemorySize_ != 0L) {
        output.writeUInt64(1, totalMemorySize_);
      }
      if (freeMemorySize_ != 0L) {
        output.writeUInt64(2, freeMemorySize_);
      }
      if (txflow_ != 0L) {
        output.writeUInt64(3, txflow_);
      }
      if (rxflow_ != 0L) {
        output.writeUInt64(4, rxflow_);
      }
      if (totalDiskSize_ != 0L) {
        output.writeUInt64(5, totalDiskSize_);
      }
      if (freeDiskSize_ != 0L) {
        output.writeUInt64(6, freeDiskSize_);
      }
      if (uptime_ != 0) {
        output.writeUInt32(7, uptime_);
      }
      if (cpuOccupy_ != 0F) {
        output.writeFloat(8, cpuOccupy_);
      }
      if (processState_ != 0) {
        output.writeUInt32(9, processState_);
      }
      if (cpuNum_ != 0) {
        output.writeUInt32(10, cpuNum_);
      }
      if (getLoadavgList().size() > 0) {
        output.writeUInt32NoTag(90);
        output.writeUInt32NoTag(loadavgMemoizedSerializedSize);
      }
      for (int i = 0; i < loadavg_.size(); i++) {
        output.writeFloatNoTag(loadavg_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (totalMemorySize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, totalMemorySize_);
      }
      if (freeMemorySize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, freeMemorySize_);
      }
      if (txflow_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, txflow_);
      }
      if (rxflow_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, rxflow_);
      }
      if (totalDiskSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, totalDiskSize_);
      }
      if (freeDiskSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, freeDiskSize_);
      }
      if (uptime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, uptime_);
      }
      if (cpuOccupy_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, cpuOccupy_);
      }
      if (processState_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, processState_);
      }
      if (cpuNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, cpuNum_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getLoadavgList().size();
        size += dataSize;
        if (!getLoadavgList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        loadavgMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Sysinfo)) {
        return super.equals(obj);
      }
      Sysinfo other = (Sysinfo) obj;

      boolean result = true;
      result = result && (getTotalMemorySize()
          == other.getTotalMemorySize());
      result = result && (getFreeMemorySize()
          == other.getFreeMemorySize());
      result = result && (getTxflow()
          == other.getTxflow());
      result = result && (getRxflow()
          == other.getRxflow());
      result = result && (getTotalDiskSize()
          == other.getTotalDiskSize());
      result = result && (getFreeDiskSize()
          == other.getFreeDiskSize());
      result = result && (getUptime()
          == other.getUptime());
      result = result && (
          Float.floatToIntBits(getCpuOccupy())
          == Float.floatToIntBits(
              other.getCpuOccupy()));
      result = result && (getProcessState()
          == other.getProcessState());
      result = result && (getCpuNum()
          == other.getCpuNum());
      result = result && getLoadavgList()
          .equals(other.getLoadavgList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTALMEMORYSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalMemorySize());
      hash = (37 * hash) + FREEMEMORYSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFreeMemorySize());
      hash = (37 * hash) + TXFLOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxflow());
      hash = (37 * hash) + RXFLOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRxflow());
      hash = (37 * hash) + TOTALDISKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotalDiskSize());
      hash = (37 * hash) + FREEDISKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFreeDiskSize());
      hash = (37 * hash) + UPTIME_FIELD_NUMBER;
      hash = (53 * hash) + getUptime();
      hash = (37 * hash) + CPUOCCUPY_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getCpuOccupy());
      hash = (37 * hash) + PROCESSSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getProcessState();
      hash = (37 * hash) + CPUNUM_FIELD_NUMBER;
      hash = (53 * hash) + getCpuNum();
      if (getLoadavgCount() > 0) {
        hash = (37 * hash) + LOADAVG_FIELD_NUMBER;
        hash = (53 * hash) + getLoadavgList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Sysinfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysinfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysinfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysinfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysinfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sysinfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sysinfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sysinfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sysinfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Sysinfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sysinfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sysinfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Sysinfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sysinfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sysinfo)
        SysinfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonHeader.internal_static_Sysinfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonHeader.internal_static_Sysinfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sysinfo.class, Builder.class);
      }

      // Construct using CommonHeader.Sysinfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        totalMemorySize_ = 0L;

        freeMemorySize_ = 0L;

        txflow_ = 0L;

        rxflow_ = 0L;

        totalDiskSize_ = 0L;

        freeDiskSize_ = 0L;

        uptime_ = 0;

        cpuOccupy_ = 0F;

        processState_ = 0;

        cpuNum_ = 0;

        loadavg_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonHeader.internal_static_Sysinfo_descriptor;
      }

      public Sysinfo getDefaultInstanceForType() {
        return Sysinfo.getDefaultInstance();
      }

      public Sysinfo build() {
        Sysinfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Sysinfo buildPartial() {
        Sysinfo result = new Sysinfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.totalMemorySize_ = totalMemorySize_;
        result.freeMemorySize_ = freeMemorySize_;
        result.txflow_ = txflow_;
        result.rxflow_ = rxflow_;
        result.totalDiskSize_ = totalDiskSize_;
        result.freeDiskSize_ = freeDiskSize_;
        result.uptime_ = uptime_;
        result.cpuOccupy_ = cpuOccupy_;
        result.processState_ = processState_;
        result.cpuNum_ = cpuNum_;
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          loadavg_ = java.util.Collections.unmodifiableList(loadavg_);
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.loadavg_ = loadavg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sysinfo) {
          return mergeFrom((Sysinfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sysinfo other) {
        if (other == Sysinfo.getDefaultInstance()) return this;
        if (other.getTotalMemorySize() != 0L) {
          setTotalMemorySize(other.getTotalMemorySize());
        }
        if (other.getFreeMemorySize() != 0L) {
          setFreeMemorySize(other.getFreeMemorySize());
        }
        if (other.getTxflow() != 0L) {
          setTxflow(other.getTxflow());
        }
        if (other.getRxflow() != 0L) {
          setRxflow(other.getRxflow());
        }
        if (other.getTotalDiskSize() != 0L) {
          setTotalDiskSize(other.getTotalDiskSize());
        }
        if (other.getFreeDiskSize() != 0L) {
          setFreeDiskSize(other.getFreeDiskSize());
        }
        if (other.getUptime() != 0) {
          setUptime(other.getUptime());
        }
        if (other.getCpuOccupy() != 0F) {
          setCpuOccupy(other.getCpuOccupy());
        }
        if (other.getProcessState() != 0) {
          setProcessState(other.getProcessState());
        }
        if (other.getCpuNum() != 0) {
          setCpuNum(other.getCpuNum());
        }
        if (!other.loadavg_.isEmpty()) {
          if (loadavg_.isEmpty()) {
            loadavg_ = other.loadavg_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureLoadavgIsMutable();
            loadavg_.addAll(other.loadavg_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sysinfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sysinfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long totalMemorySize_ ;
      /**
       * <code>uint64 totalMemorySize = 1;</code>
       */
      public long getTotalMemorySize() {
        return totalMemorySize_;
      }
      /**
       * <code>uint64 totalMemorySize = 1;</code>
       */
      public Builder setTotalMemorySize(long value) {
        
        totalMemorySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 totalMemorySize = 1;</code>
       */
      public Builder clearTotalMemorySize() {
        
        totalMemorySize_ = 0L;
        onChanged();
        return this;
      }

      private long freeMemorySize_ ;
      /**
       * <code>uint64 freeMemorySize = 2;</code>
       */
      public long getFreeMemorySize() {
        return freeMemorySize_;
      }
      /**
       * <code>uint64 freeMemorySize = 2;</code>
       */
      public Builder setFreeMemorySize(long value) {
        
        freeMemorySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 freeMemorySize = 2;</code>
       */
      public Builder clearFreeMemorySize() {
        
        freeMemorySize_ = 0L;
        onChanged();
        return this;
      }

      private long txflow_ ;
      /**
       * <code>uint64 txflow = 3;</code>
       */
      public long getTxflow() {
        return txflow_;
      }
      /**
       * <code>uint64 txflow = 3;</code>
       */
      public Builder setTxflow(long value) {
        
        txflow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 txflow = 3;</code>
       */
      public Builder clearTxflow() {
        
        txflow_ = 0L;
        onChanged();
        return this;
      }

      private long rxflow_ ;
      /**
       * <code>uint64 rxflow = 4;</code>
       */
      public long getRxflow() {
        return rxflow_;
      }
      /**
       * <code>uint64 rxflow = 4;</code>
       */
      public Builder setRxflow(long value) {
        
        rxflow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rxflow = 4;</code>
       */
      public Builder clearRxflow() {
        
        rxflow_ = 0L;
        onChanged();
        return this;
      }

      private long totalDiskSize_ ;
      /**
       * <code>uint64 totalDiskSize = 5;</code>
       */
      public long getTotalDiskSize() {
        return totalDiskSize_;
      }
      /**
       * <code>uint64 totalDiskSize = 5;</code>
       */
      public Builder setTotalDiskSize(long value) {
        
        totalDiskSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 totalDiskSize = 5;</code>
       */
      public Builder clearTotalDiskSize() {
        
        totalDiskSize_ = 0L;
        onChanged();
        return this;
      }

      private long freeDiskSize_ ;
      /**
       * <code>uint64 freeDiskSize = 6;</code>
       */
      public long getFreeDiskSize() {
        return freeDiskSize_;
      }
      /**
       * <code>uint64 freeDiskSize = 6;</code>
       */
      public Builder setFreeDiskSize(long value) {
        
        freeDiskSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 freeDiskSize = 6;</code>
       */
      public Builder clearFreeDiskSize() {
        
        freeDiskSize_ = 0L;
        onChanged();
        return this;
      }

      private int uptime_ ;
      /**
       * <code>uint32 uptime = 7;</code>
       */
      public int getUptime() {
        return uptime_;
      }
      /**
       * <code>uint32 uptime = 7;</code>
       */
      public Builder setUptime(int value) {
        
        uptime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uptime = 7;</code>
       */
      public Builder clearUptime() {
        
        uptime_ = 0;
        onChanged();
        return this;
      }

      private float cpuOccupy_ ;
      /**
       * <code>float cpuOccupy = 8;</code>
       */
      public float getCpuOccupy() {
        return cpuOccupy_;
      }
      /**
       * <code>float cpuOccupy = 8;</code>
       */
      public Builder setCpuOccupy(float value) {
        
        cpuOccupy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float cpuOccupy = 8;</code>
       */
      public Builder clearCpuOccupy() {
        
        cpuOccupy_ = 0F;
        onChanged();
        return this;
      }

      private int processState_ ;
      /**
       * <code>uint32 processState = 9;</code>
       */
      public int getProcessState() {
        return processState_;
      }
      /**
       * <code>uint32 processState = 9;</code>
       */
      public Builder setProcessState(int value) {
        
        processState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 processState = 9;</code>
       */
      public Builder clearProcessState() {
        
        processState_ = 0;
        onChanged();
        return this;
      }

      private int cpuNum_ ;
      /**
       * <code>uint32 cpuNum = 10;</code>
       */
      public int getCpuNum() {
        return cpuNum_;
      }
      /**
       * <code>uint32 cpuNum = 10;</code>
       */
      public Builder setCpuNum(int value) {
        
        cpuNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cpuNum = 10;</code>
       */
      public Builder clearCpuNum() {
        
        cpuNum_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Float> loadavg_ = java.util.Collections.emptyList();
      private void ensureLoadavgIsMutable() {
        if (!((bitField0_ & 0x00000400) == 0x00000400)) {
          loadavg_ = new java.util.ArrayList<Float>(loadavg_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public java.util.List<Float>
          getLoadavgList() {
        return java.util.Collections.unmodifiableList(loadavg_);
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public int getLoadavgCount() {
        return loadavg_.size();
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public float getLoadavg(int index) {
        return loadavg_.get(index);
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public Builder setLoadavg(
          int index, float value) {
        ensureLoadavgIsMutable();
        loadavg_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public Builder addLoadavg(float value) {
        ensureLoadavgIsMutable();
        loadavg_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public Builder addAllLoadavg(
          Iterable<? extends Float> values) {
        ensureLoadavgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, loadavg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float loadavg = 11;</code>
       */
      public Builder clearLoadavg() {
        loadavg_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Sysinfo)
    }

    // @@protoc_insertion_point(class_scope:Sysinfo)
    private static final Sysinfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Sysinfo();
    }

    public static Sysinfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sysinfo>
        PARSER = new com.google.protobuf.AbstractParser<Sysinfo>() {
      public Sysinfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sysinfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sysinfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Sysinfo> getParserForType() {
      return PARSER;
    }

    public Sysinfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Common_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sysinfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Sysinfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014Common.proto\"R\n\006Common\022\021\n\tprotoType\030\001 " +
      "\001(\005\022\r\n\005verNo\030\002 \001(\005\022\023\n\013commandType\030\003 \001(\005\022" +
      "\021\n\trequestId\030\004 \001(\005\"\341\001\n\007Sysinfo\022\027\n\017totalM" +
      "emorySize\030\001 \001(\004\022\026\n\016freeMemorySize\030\002 \001(\004\022" +
      "\016\n\006txflow\030\003 \001(\004\022\016\n\006rxflow\030\004 \001(\004\022\025\n\rtotal" +
      "DiskSize\030\005 \001(\004\022\024\n\014freeDiskSize\030\006 \001(\004\022\016\n\006" +
      "uptime\030\007 \001(\r\022\021\n\tcpuOccupy\030\010 \001(\002\022\024\n\014proce" +
      "ssState\030\t \001(\r\022\016\n\006cpuNum\030\n \001(\r\022\017\n\007loadavg" +
      "\030\013 \003(\002B\016B\014CommonHeaderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Common_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Common_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Common_descriptor,
        new String[] { "ProtoType", "VerNo", "CommandType", "RequestId", });
    internal_static_Sysinfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Sysinfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Sysinfo_descriptor,
        new String[] { "TotalMemorySize", "FreeMemorySize", "Txflow", "Rxflow", "TotalDiskSize", "FreeDiskSize", "Uptime", "CpuOccupy", "ProcessState", "CpuNum", "Loadavg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
